name: actionlint
on:
  repository_dispatch:
      types: [actionlint]
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        shell: pwsh
        run: |
          .\build.ps1 -target actionlint -owner rhysd
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: actionlint Updated
