name: tofu
on:
  repository_dispatch:
    types: [tofu]
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  update-tofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        shell: pwsh
        run: |
          .\build.ps1 -target opentofu -owner opentofu
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: tofu Updated
